execution_engine: asyncio
logger:
  type: file
  level: debug
  batch_size: 100
  flush_interval: 2
  max_queue_size: 2048
  http_endpoint:
  http_headers:
  http_timeout: 5

mcp:
  servers:
    mcp_agent:
      command: "uv"
      args: ["run", "server.py"]
    fetch:
      command: "uvx"
      args: ["mcp-server-fetch"]
    filesystem:
      command: "npx"
      args:
        [
          "-y",
          "@modelcontextprotocol/server-filesystem",
          "/Users/eddie.rowe/Downloads",
          "/Users/eddie.rowe/Repos/vertical-farm/"
        ]
    sequential_thinking:
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-sequential-thinking"]
    playwright:
      command: "npx"
      args: ["-y", "@executeautomation/playwright-mcp-server"]

openai:
  # Secrets (API keys, etc.) are stored in an mcp_agent.secrets.yaml file which can be gitignored
  default_model: gpt-4o