# Example Cloudflare Configuration
# Copy this file to config.toml and update with your values

[account]
id = "your_account_id_here"
api_token = "your_api_token_here"
zone_id = "your_zone_id_here"

[domain]
name = "yourdomain.com"
subdomain = "app"  # Optional: app.yourdomain.com

[supabase]
url = "https://your-project.supabase.co"
anon_key = "your_supabase_anon_key"
service_role_key = "your_SUPABASE_SERVICE_KEY"

[kv_namespaces]
device_cache = "your_kv_namespace_id"
device_cache_preview = "your_preview_kv_namespace_id"

[workers]
cpu_limit = 50
memory_limit = 128

[security.rate_limits]
api_general = 100      # requests per minute
sensors = 300          # requests per minute  
auth = 10             # requests per 5 minutes
device_registration = 5 # requests per hour

[cache.ttl]
static_assets = 2592000  # 30 days in seconds
dashboard = 300          # 5 minutes
public_pages = 3600      # 1 hour
api_responses = 0        # no cache 