name = "vertical-farm"
main = "src/index.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Account configuration - uses environment variable
account_id = "${CLOUDFLARE_ACCOUNT_ID}"

# Environment variables
[env.production.vars]
ENVIRONMENT = "production"
SUPABASE_URL = "${SUPABASE_URL}"
SUPABASE_ANON_KEY = "${SUPABASE_ANON_KEY}"

[env.development.vars]
ENVIRONMENT = "development"
SUPABASE_URL = "${SUPABASE_DEV_URL}"
SUPABASE_ANON_KEY = "${SUPABASE_DEV_ANON_KEY}"

# KV Namespaces
[[kv_namespaces]]
binding = "DEVICE_CACHE"
id = "${CLOUDFLARE_KV_NAMESPACE_ID}"
preview_id = "${CLOUDFLARE_KV_PREVIEW_ID}"

# Rate limiting
[limits]
cpu_ms = 50

# Build configuration
[build]
command = "npm run build"
cwd = "workers"

# Routes for different workers
[[routes]]
pattern = "api.${DOMAIN}/sensors/*"
zone_name = "${DOMAIN}"
custom_domain = true

[[routes]]
pattern = "${DOMAIN}/api/auth/*"
zone_name = "${DOMAIN}"
custom_domain = true 