#!/bin/bash
# Script to create .env.local from Supabase status
# Uses JSON parsing for reliability

set -e

echo "Creating .env.local from Supabase status..."
echo ""

# Check if Supabase is running
if ! supabase status &>/dev/null; then
    echo "❌ Supabase is not running!"
    echo "Start it with: supabase start"
    exit 1
fi

# Get Supabase status as JSON for reliable parsing
SUPABASE_STATUS=$(supabase status --output json 2>/dev/null)

if [ -z "$SUPABASE_STATUS" ]; then
    echo "❌ Failed to get Supabase status"
    exit 1
fi

# Parse JSON output with jq (preferred) or fallback to text parsing
if command -v jq &>/dev/null; then
    echo "Using jq for reliable JSON parsing..."
    ANON_KEY=$(echo "$SUPABASE_STATUS" | jq -r '.ANON_KEY // .anon_key // empty')
    SERVICE_KEY=$(echo "$SUPABASE_STATUS" | jq -r '.SERVICE_ROLE_KEY // .service_role_key // empty')
    JWT_SECRET=$(echo "$SUPABASE_STATUS" | jq -r '.JWT_SECRET // .jwt_secret // empty')
    API_URL=$(echo "$SUPABASE_STATUS" | jq -r '.API_URL // .api_url // "http://localhost:54321"')
else
    echo "⚠️  jq not found, falling back to text parsing"
    echo "   Install jq for more reliable parsing: brew install jq"
    echo ""
    ANON_KEY=$(supabase status | grep -i "anon key" | awk '{print $NF}')
    SERVICE_KEY=$(supabase status | grep -i "service_role key" | awk '{print $NF}')
    JWT_SECRET=$(supabase status | grep -i "JWT secret" | awk '{print $NF}')
    API_URL="http://localhost:54321"
fi

# Validate extracted keys
if [ -z "$ANON_KEY" ]; then
    echo "❌ Failed to extract ANON_KEY from Supabase status"
    echo "   Try running 'supabase status' to see the output format"
    exit 1
fi

if [ -z "$SERVICE_KEY" ]; then
    echo "❌ Failed to extract SERVICE_KEY from Supabase status"
    exit 1
fi

if [ -z "$JWT_SECRET" ]; then
    echo "⚠️  JWT_SECRET not found (may be normal for some Supabase versions)"
    JWT_SECRET="local-jwt-secret-placeholder"
fi

# Create .env.local file
cat > .env.local << EOF
# ===========================================
# Vertical Farm - Local Development Environment
# ===========================================
# Auto-generated by scripts/create-env-local.sh
# Project ref: lvjhhvxwxeeupamyahmr

# -----------------------------------------
# Supabase Configuration (Local CLI)
# -----------------------------------------
SUPABASE_URL=$API_URL
SUPABASE_ANON_KEY=$ANON_KEY
SUPABASE_SERVICE_KEY=$SERVICE_KEY
SUPABASE_JWT_SECRET=$JWT_SECRET

# -----------------------------------------
# Next.js Frontend (Public Variables)
# -----------------------------------------
NEXT_PUBLIC_SUPABASE_URL=$API_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY
NEXT_PUBLIC_API_URL=http://localhost:8000

# -----------------------------------------
# Backend Configuration
# -----------------------------------------
BACKEND_CORS_ORIGINS=["http://localhost:3000","http://localhost:8000","http://host.docker.internal:3000"]
PROJECT_NAME=vertical-farm
API_V1_STR=/api/v1
DEBUG=true
ENVIRONMENT=local
FRONTEND_HOST=http://localhost:3000
SECRET_KEY=local-development-secret-change-in-production

# -----------------------------------------
# Integrations (Disabled for Local Dev)
# -----------------------------------------
# Home Assistant integration
HOME_ASSISTANT_ENABLED=false
# HOME_ASSISTANT_URL=http://your-ha-instance:8123
# HOME_ASSISTANT_TOKEN=your-long-lived-access-token

# Square integration will show "Not Connected" without config
# Add credentials if you want to test Square locally:
# SQUARE_ACCESS_TOKEN=your-sandbox-token
# SQUARE_ENVIRONMENT=sandbox
EOF

echo ""
echo "✅ Created .env.local with Supabase credentials"
echo ""
echo "📍 Local Services:"
echo "   Supabase API:    $API_URL"
echo "   Supabase Studio: http://localhost:54323"
echo "   Frontend:        http://localhost:3000"
echo "   Backend API:     http://localhost:8000"
echo ""
echo "🔑 Test Credentials:"
echo "   Email:    testuser123@gmail.com"
echo "   Password: password123"
echo ""
echo "📝 Next steps:"
echo "   docker-compose -f docker-compose.local.yml --env-file .env.local up -d"
