#!/bin/bash

# Create environment template files for developers

echo "📝 Creating environment template files..."

# Create .env.local.example
cat > .env.local.example << 'EOF'
# Local Development Environment Variables
# This file is auto-generated by setup-local-dev.sh
# DO NOT EDIT THIS FILE DIRECTLY - it will be overwritten

# === Supabase Local (auto-populated) ===
SUPABASE_URL=http://localhost:54321
NEXT_PUBLIC_SUPABASE_URL=http://localhost:54321
SUPABASE_ANON_KEY=will-be-auto-populated
NEXT_PUBLIC_SUPABASE_ANON_KEY=will-be-auto-populated
SUPABASE_SERVICE_KEY=will-be-auto-populated
SUPABASE_JWT_SECRET=will-be-auto-populated

# === API Configuration ===
NEXT_PUBLIC_API_URL=http://localhost:8000
BACKEND_CORS_ORIGINS=["http://localhost:3000","http://localhost:8000"]
FRONTEND_HOST=http://localhost:3000
PROJECT_NAME=vertical-farm-local
API_V1_STR=/api/v1
DEBUG=true
ENVIRONMENT=local

# === Security ===
SECRET_KEY=local-development-secret-key
ACCESS_TOKEN_EXPIRE_MINUTES=30

# === Datadog (Optional) ===
DD_API_KEY=
DD_SITE=datadoghq.com
DD_SERVICE=vertical-farm-local
DD_ENV=local

# === Background Tasks ===
BACKGROUND_TASKS_ENABLED=true
BACKGROUND_TASK_SYSTEM=supabase
EOF

# Create .env.production.example
cat > .env.production.example << 'EOF'
# Production Environment Variables Template
# Copy this to .env.production and fill with real values
# NEVER COMMIT .env.production TO GIT!

# === Supabase Production ===
SUPABASE_URL=https://your-project.supabase.co
NEXT_PUBLIC_SUPABASE_URL=https://your-project.supabase.co
SUPABASE_ANON_KEY=your-production-anon-key
NEXT_PUBLIC_SUPABASE_ANON_KEY=your-production-anon-key
SUPABASE_SERVICE_KEY=your-production-service-key
SUPABASE_JWT_SECRET=your-production-jwt-secret

# === API Configuration ===
NEXT_PUBLIC_API_URL=https://api.your-domain.com
BACKEND_CORS_ORIGINS=["https://your-domain.com","https://api.your-domain.com"]
FRONTEND_HOST=https://your-domain.com
PROJECT_NAME=vertical-farm
API_V1_STR=/api/v1
DEBUG=false
ENVIRONMENT=production

# === Security ===
SECRET_KEY=your-production-secret-key
ACCESS_TOKEN_EXPIRE_MINUTES=30

# === Datadog Production ===
DD_API_KEY=your-datadog-api-key
DD_SITE=datadoghq.com
DD_SERVICE=vertical-farm
DD_ENV=production
NEXT_PUBLIC_DD_RUM_APPLICATION_ID=your-rum-app-id
NEXT_PUBLIC_DD_RUM_CLIENT_TOKEN=your-rum-client-token
NEXT_PUBLIC_DD_SITE=datadoghq.com
NEXT_PUBLIC_DD_SERVICE=vertical-farm-frontend
NEXT_PUBLIC_DD_ENV=production

# === Background Tasks ===
BACKGROUND_TASKS_ENABLED=true
BACKGROUND_TASK_SYSTEM=supabase

# === Database Monitoring ===
SUPABASE_METRICS_URL=
POSTGRES_DATADOG_USERNAME=
POSTGRES_DATADOG_PASSWORD=
POSTGRES_DATADOG_DBNAME=
EOF

echo "✅ Created template files:"
echo "  - .env.local.example (for reference)"
echo "  - .env.production.example (for testing prod config locally)"
echo ""
echo "💡 Note: .env.local is auto-generated by setup-local-dev.sh"
echo "💡 To test with production config locally:"
echo "   1. Copy .env.production.example to .env.production"
echo "   2. Fill in your production values"
echo "   3. Run: make test-prod"
