#!/bin/bash
# Generate .act-secrets from Supabase status for local CI testing with nektos/act
# This ensures your local GitHub Actions runs have the same credentials as your dev environment

set -e

echo "Creating .act-secrets from Supabase status..."
echo ""

# Check if Supabase is running
if ! supabase status &>/dev/null; then
    echo "Supabase is not running!"
    echo "Start it with: supabase start"
    exit 1
fi

# Get Supabase status as JSON for reliable parsing
SUPABASE_STATUS=$(supabase status --output json 2>/dev/null)

if [ -z "$SUPABASE_STATUS" ]; then
    echo "Failed to get Supabase status"
    exit 1
fi

# Parse JSON output with jq (preferred) or fallback to text parsing
if command -v jq &>/dev/null; then
    echo "Using jq for reliable JSON parsing..."
    ANON_KEY=$(echo "$SUPABASE_STATUS" | jq -r '.ANON_KEY // .anon_key // empty')
    SERVICE_KEY=$(echo "$SUPABASE_STATUS" | jq -r '.SERVICE_ROLE_KEY // .service_role_key // empty')
    API_URL=$(echo "$SUPABASE_STATUS" | jq -r '.API_URL // .api_url // "http://localhost:54321"')
else
    echo "jq not found, falling back to text parsing"
    echo "   Install jq for more reliable parsing: brew install jq"
    echo ""
    ANON_KEY=$(supabase status | grep -i "anon key" | awk '{print $NF}')
    SERVICE_KEY=$(supabase status | grep -i "service_role key" | awk '{print $NF}')
    API_URL="http://localhost:54321"
fi

# Validate extracted keys
if [ -z "$ANON_KEY" ]; then
    echo "Failed to extract ANON_KEY from Supabase status"
    echo "   Try running 'supabase status' to see the output format"
    exit 1
fi

if [ -z "$SERVICE_KEY" ]; then
    echo "Failed to extract SERVICE_KEY from Supabase status"
    exit 1
fi

# Create .act-secrets file
cat > .act-secrets << EOF
# Auto-generated secrets for nektos/act local CI testing
# Generated by scripts/create-act-secrets.sh
# Do not commit this file!

# Supabase credentials
SUPABASE_URL=$API_URL
SUPABASE_ANON_KEY=$ANON_KEY
SUPABASE_SERVICE_KEY=$SERVICE_KEY

# Next.js public environment variables
NEXT_PUBLIC_SUPABASE_URL=$API_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY

# Testing flag
TESTING=true

# Additional CI environment
CI=true
GITHUB_ACTIONS=true
EOF

echo ""
echo "Created .act-secrets with Supabase credentials"
echo ""
echo "Local Services:"
echo "   Supabase API:    $API_URL"
echo "   Supabase Studio: http://localhost:54323"
echo ""
echo "Next steps:"
echo "   Run local CI with: act -j backend-tests"
echo "   Or use: /test (Claude Code command)"
