name = "vertical-farm-static-cache"
main = "index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Account configuration
account_id = "${CLOUDFLARE_ACCOUNT_ID}"

# Environment variables
[vars]
STATIC_TTL = "86400"      # 1 day for regular static files
IMMUTABLE_TTL = "31536000" # 1 year for hashed/immutable files
HTML_TTL = "300"          # 5 minutes for HTML pages
ORIGIN_URL = "${FRONTEND_PROD_URL}"

# KV namespace binding for assets
[[kv_namespaces]]
binding = "ASSETS_KV"
id = "${CLOUDFLARE_ASSETS_KV_NAMESPACE_ID}"
preview_id = "${CLOUDFLARE_ASSETS_KV_PREVIEW_ID}"

# Routes for static assets
routes = [
  { pattern = "${CDN_DOMAIN}/*", zone_name = "${DOMAIN}" }
] 