# GitHub Pages configuration for static Markdown site
# This file is optional, but can be used for basic navigation if using Jekyll (not required with .nojekyll)
title: Vertical Farm Documentation
description: Documentation for the Vertical Farm project
