name: Deploy Supabase Migrations to Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Set up environment
        run: |
          echo "SUPABASE_ACCESS_TOKEN=${{ secrets.SUPABASE_ACCESS_TOKEN_DEV }}" >> $GITHUB_ENV
          echo "SUPABASE_DB_URL=${{ secrets.SUPABASE_DB_URL_DEV }}" >> $GITHUB_ENV

      - name: Push migrations to Dev
        run: |
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF_DEV }}
          supabase db push --db-url $SUPABASE_DB_URL
