name: Deploy on unRAID
on:
  workflow_run:
    workflows: ["Build & push image"]
    types:
      - completed
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted   # will hit your unRAID runner
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      # ----- DEPLOY LOCALLY ON UNRAID -----
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Pull & restart backend container
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/backend:${{ github.sha }}
          CONTAINER=backend
          # pull new image
          docker pull $IMAGE
          # stop/remove old container if it exists
          docker rm -f $CONTAINER 2>/dev/null || true
          # launch with your desired flags
          docker run -d --name $CONTAINER --restart unless-stopped \
            -p 8000:8000 \
            $IMAGE

      - name: Pull & restart frontend container
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/frontend:${{ github.sha }}
          CONTAINER=frontend
          # pull new image
          docker pull $IMAGE
          # stop/remove old container if it exists
          docker rm -f $CONTAINER 2>/dev/null || true
          # launch with your desired flags
          docker run -d --name $CONTAINER --restart unless-stopped \
            -p 3000:3000 \
            $IMAGE